import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "@/components/AuthProvider/AuthProvider";
const inter = Inter({ subsets: ["latin"] });
import { ThemeProvider } from "@/components/theme-provider"
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
          <html lang="en">
            <body className={inter.className}>
              <AuthProvider>
              
                  <div className="max-w-10xl mx-auto ">
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                     >
                    <Navbar />
                    <div className="mt-8">
                      {children}  
                      </div>
                     </ThemeProvider>           
                  </div>
              </AuthProvider>
            </body>
          </html>
  );
}
